config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  root 'static_pages#home'

  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :microposts,          only: [:create, :destroy]
  resources :statuses,          only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  resources :microposts do
    resources :comments
    member do
      put "like", to: "microposts#like"
      put "dislike", to: "microposts#dislike"
    end
  end

  resources :comments do
    member do
      put "like", to: "comments#like"
      put "dislike", to: "comments#dislike"
    end
  end
  get 'notifications/:id/link_through', to: 'notifications#link_through',
  as: :link_through
  get 'notifications', to: 'notifications#index'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :logged_in_user, only: [:show,:create, :destroy]

  layout false

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversations.html.erb
<% @conversations.order('created_at DESC').limit(6).each do |conversation| %>
<li>
  <div class="row">
    <%= link_to "", conversation_path(conversation), class: "conversation", "data-cid" => conversation.id %>
    <div class="col s1">
      <% if conversation_interlocutor(conversation).picture? %>
      <%= image_tag conversation_interlocutor(conversation).picture.url ,:style =>'width:100%'%>
      <% else %>
      <%= image_tag 'default-image.png' ,:style =>'width:100%'%>
      <% end %>
    </div>
    <div class="s11">
      <div class="row">
        <%= conversation_interlocutor(conversation).first_name %>
      </div>
      <div class="row">
        <p>
          <% if !conversation.messages.last.nil? %>
          <%= truncate(conversation.messages.last.body, length: 45) %>
        </p>
        <% end %>
      </div>
    </div>
  </div>
</li>
<% end %>

app/views/conversations/show.html.erb
<%= javascript_include_tag 'users.js'%>

<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.first_name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
  <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => { id: "conversation_form_#{@conversation.id}"}) do |f| %>
  <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>