config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  root 'static_pages#home'

  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :microposts,          only: [:create, :destroy]
  resources :statuses,          only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  resources :microposts do
    resources :comments
    member do
      put "like", to: "microposts#like"
      put "dislike", to: "microposts#dislike"
    end
  end

  resources :comments do
    member do
      put "like", to: "comments#like"
      put "dislike", to: "comments#dislike"
    end
  end
  get 'notifications/:id/link_through', to: 'notifications#link_through',
  as: :link_through
  get 'notifications', to: 'notifications#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :user
	belongs_to :notified_by, class_name: 'User'  
	belongs_to :micropost
	validates :user_id, :notified_by_id, :micropost_id, :notice_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	def link_through
		@notification = Notification.find(params[:id])
		@notification.update read: true
		redirect_to micropost_path @notification.micropost
		@users = User.all
	end
	def index
		@conversations = Conversation.involving(current_user).order("created_at DESC")
		@notifications = current_user.notifications
		@users = User.all
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li>
<%= link_to "#{notification.notified_by.first_name} has #{notification.notice_type}ed on your post", micropost_path(notification.micropost) %>
</li>

app/views/notifications/_notifications.html.erb
 <% current_user.notifications.order('created_at DESC').limit(6).each do |notification| %>
 <% if notification.read == false %>
 <li style="background-color:#EE6E73;color:black !important">
  <div class="row" style="margin-bottom:0">
   <div class="col s2">
    <% if notification.notified_by.picture? %>
    <%= image_tag notification.notified_by.picture.url ,:style =>'width:100%'%>
    <% else %>
    <%= image_tag 'default-image.png' ,:style =>'width:100%'%>
    <% end %>
  </div>
  <div class="col s9">
    <div class="row" style="margin-bottom:0">
      <% if notification.user_id == current_user.id && notification.identifier != nil%>
      <%= link_to "#{notification.notified_by.first_name} has #{notification.notice_type}ed on your post", link_through_path(notification),:style => 'color:black;padding:0' %>
      <% elsif notification.identifier == nil %>
      <%= link_to "#{notification.notified_by.first_name} has #{notification.notice_type}", link_through_path(notification),:style => 'color:black;padding:0' %>
      <% end %>
    </div>
    <div class="row" style="margin-bottom:0">
     <%= time_ago_in_words(notification.created_at) %> ago.
   </div>
 </div>
</div>

</li>
<% else %>
<li style="color:black !important">
  <div class="row" style="margin-bottom:0">
    <div class="col s2">
      <% if notification.notified_by.picture? %>
      <%= image_tag notification.notified_by.picture.url ,:style =>'width:100%'%>
      <% else %>
      <%= image_tag 'default-image.png' %>
      <% end %>
    </div>
    <div class="col s9">
      <div class="row" style="margin-bottom:0">
        <% if notification.identifier == nil %>
        <%= link_to "#{notification.notified_by.first_name} has #{notification.notice_type}ed his status", link_through_path(notification) ,:style => 'color:black;padding:0'%>
        <% else %>
        <%= link_to "#{notification.notified_by.first_name} has #{notification.notice_type}ed on your post", link_through_path(notification) ,:style => 'color:black;padding:0'%>
        <% end %>
      </div>
      <div class="row" style="margin-bottom:0">
       <%= time_ago_in_words(notification.created_at) %> ago.
     </div>
   </div>
 </div>

</li>
<% end %>
<% end %>
<li>
  <%= link_to 'View All', notifications_path ,:class =>'center-align'%>
</li>

app/views/notifications/index.html.erb
<%= render @notifications %>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>