config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  root 'static_pages#home'

  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :microposts,          only: [:create, :destroy]
  resources :statuses,          only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  resources :microposts do
    resources :comments
    member do
      put "like", to: "microposts#like"
      put "dislike", to: "microposts#dislike"
    end
  end

  resources :comments do
    member do
      put "like", to: "comments#like"
      put "dislike", to: "comments#dislike"
    end
  end
  get 'notifications/:id/link_through', to: 'notifications#link_through',
  as: :link_through
  get 'notifications', to: 'notifications#index'

end

app/views/layouts/_header.html.erb
<div class="navbar-fixed">
  <nav style="background-color: #2A80BA">
    <div class="nav-wrapper">
      <%= link_to "Connector", root_path, id: "logo" ,class: "brand-logo"%>
      <a href="#" data-activates="mobile-demo" class="button-collapse">
        <i class="material-icons">menu</i>
      </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
        </li>
        <% if logged_in? %>
        <li>
          <%= form_tag(users_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Connector" %>
          <%= submit_tag "Search" ,:style =>'display:none'%>
          <% end %>
          <% user_array = Array.new %>
          <% @users.each do |user| %>
          <% user_array.push(user.first_name+" "+user.last_name) %>
          <% end %>
        </li>
        <li>
          <%= link_to current_user.first_name, current_user %>
        </li>
        <li>
          <a class='dropdown-button' href='#' data-activates='dropdown12' data-beloworigin="true"><i class="fa fa-envelope-o"></i>
            <sup>
              <%= current_user.conversations.count %>
            </sup>
          </i></a>
          <ul id='dropdown12' class='dropdown-content'>
            <li>Messages</li>
            <% if @conversations.any? && logged_in?%>
            <%=render 'conversations/conversations' %>
            <% else %>
            <p>You have no conversations. Click send message with any user to create one.</p>
            <% end %>
          </ul>
        </li>
        <li>
          <a class='dropdown-button' href='#' data-activates='dropdown11'">
            <i class="fa fa-bell"></i>
            <sup>
              <%= current_user.notifications.where(read:false).count %>
            </sup>
          </a>
          <!-- Dropdown Structure -->
          <ul id='dropdown11' class='notify-list'>
            <li class="head" style="text-align:center">Notification</li>
            <%= render 'notifications/notifications' %>
          </ul>
        </li>
        <% if current_user.admin?%>
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <% end %>
        <li class="dropdown">
         <a class='dropdown-button btn' href='#' data-activates='dropdown13' data-beloworigin="true">
           Account
         </a>
         <ul id='dropdown13' class='dropdown-content'>
          <li>
            <%= link_to "Profile", current_user %>
          </li>
          <li>
            <%= link_to "Settings", '#update_profile',:class=>'update_profile' %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        </ul>
      </a>
    </li>
    <% else %>
    <li>
      <ul>
       <%= form_for(:session, url: login_path) do |f| %>
       <li>
        <%= f.email_field :email, :placeholder =>'Email' %>
      </li>
      <li>
        <%= f.password_field :password, class: 'form-control' ,:placeholder =>'Password'%>
      </li>
      <%= f.submit "Log in", class: "btn btn-primary" %>
      <% end %>
    </ul>
  </li>
  <% end %>
</ul>
<ul class="side-nav" id="mobile-demo" style="transform: translateX(0%);display:none">
  <%= render 'layouts/header_content' %>
</ul>
</div>
</nav>
</div>
<div id="update_profile" class="modal">
  <div class="modal-content">
    <h4>Update Profile</h4>
    <p class="user_data"></p>
  </div>
  <div class="modal-footer">
    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
  </div>
</div>
<% if logged_in?%>
<script type="text/javascript">
  $(function() {
    $(".button-collapse").sideNav();
    $('.update_profile').leanModal();
    $('.update_profile').click(function(){
      $('.user_data').append('<%= form_for(@user) do |f| %><%= render 'shared/error_messages', object: f.object %> <%= f.label :first_name %> <%= f.text_field :first_name, class: 'form-control' %> <%= f.label :last_name %> <%= f.text_field :last_name, class: 'form-control' %> <%= f.label :email %> <%= f.email_field :email, class: 'form-control' %> <%= f.label :mobile %> <%= f.number_field :mobile,only_integer: true, class: 'form-control' %> <%= f.label :password %> <%= f.password_field :password, class: 'form-control' %> <%= f.label :password_confirmation, "Confirmation" %> <%= f.password_field :password_confirmation, class: 'form-control' %> <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' ,id: 'user_picture'%> <%= f.submit "Save changes", class: "btn btn-primary" %> <% end %>')
    });
    /*** look into it***/
    $('#user_picture').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
    });
    var availableTags = [];
    var ar = "<%= user_array %>";
    while(ar.search("&quot;")>0){

      ar = ar.replace ('&quot;','"');
    }
    //console.log(ar);
    availableTags = JSON.parse(ar);
    //console.log(availableTags);
    $( "#tags" ).autocomplete({
      source: availableTags
    });
    $("#tags").bind('keydown',function(e){
     if(e.keyCode == 13) {
      $.ajax({url:'/users/1'});
    }
  });

  });
</script>

<%end%>

app/views/layouts/_header_content.html.erb
<ul>
  <li>
  </li>
  <% if logged_in? %>
  <li>
    <%= form_tag(users_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
    <%= submit_tag "Search" ,:style =>'display:none'%>
    <% end %>
  </li>
  <li>
    <%= link_to current_user.first_name, current_user %>
  </li>
  <li style="color:black;">
    <i class="fa fa-envelope-o"></i>Messages
  </li>
  <li>
    <%= link_to '<i class="fa fa-bell"></i><sup>'.html_safe + ""+ current_user.notifications.where(read:false).count + "" +"</sup> Notifications".html_safe,notifications_path %>
  </li>
  <% if current_user.admin?%>
  <li>
    <%= link_to "Users", users_path %>
  </li>
  <% end %>
  <li class="dropdown">
   <a class='dropdown-button btn' href='#' data-activates='dropdown1' data-beloworigin="true">
     Account
   </a>
   <ul id='dropdown1' class='dropdown-content'>
    <li>
      <%= link_to "Profile", current_user %>
    </li>
    <li>
      <%= link_to "Settings", edit_user_path(current_user) %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to "Log out", logout_path, method: "delete" %>
    </li>
  </ul>
</a>
</li>
<% else %>
<li>
  <ul>
   <%= form_for(:session, url: login_path) do |f| %>
   <li>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </li>
  <li>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </li>
  <%= f.submit "Log in", class: "btn btn-primary" %>
  <% end %>
</ul>
</li>
<% end %>
</ul>

app/views/layouts/_side_nav.html.erb
<div class="row">
  <ul>
    <li><%= link_to '<i class="tiny material-icons perm_identity">perm_identity
    </i>'.html_safe+ " " +current_user.first_name + " " + current_user.last_name,current_user %>
  </li>
  <li><%= link_to '<i class="tiny material-icons mode_edit">mode_edit</i> Edit Profile'.html_safe, edit_user_path(current_user) %></li>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='<%= logged_in? ? current_user.id : "" %>' name='user-id'/>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <title><%if logged_in?%><%= current_user.first_name%> : <%end%>Connector</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= stylesheet_link_tag    'font-awesome-icons', media: 'all'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= notice %>
  <%= render 'layouts/header' %>
  <%= yield %>
  <audio id="chatAudio"><source src="/sounds/notification.mp3" type="audio/mpeg"></audio>

</body>
</html>